services:


  postgres:
    image: pgvector/pgvector:pg15
    # build:
    #   context: ./backend/db
    #   dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    ports:
      - 5434:5432
    networks:
      - main

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - './frontend:/app'
  #     - './frontend/node_modules:/app/node_modules'
  #   ports:
  #     - '3001:3001'

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.prod
  #   ports:
  #     - '1337:80'
  #   networks:
  #     - main

  backend: &backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/home/app/backend
    ports:
      - 8000:8000
    # logging: *default-logging 
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3 
    networks:
      - main  
    

volumes:
  postgres_data:

networks:
  main:
    name: images_network
    driver: bridge