"""add img

Revision ID: 70c810d3cbe5
Revises: b65bdedb0945
Create Date: 2025-01-03 00:48:00.892136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70c810d3cbe5'
down_revision: Union[str, None] = 'b65bdedb0945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['public.profiles.id'], name='img2profile'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__images')),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images', schema='public')
    # ### end Alembic commands ###
